### ISSUE TITLE
Crash on launch [Optifine pre13]

### ISSUE THREAD

**Issue by AltoIgloo** [Draylar/inmis#10]
[crash-2020-04-04_19.10.12-client.txt](https://github.com/Draylar/inmis/files/4431216/crash-2020-04-04_19.10.12-client.txt)
Here's the crash report.

**Comment by Draylar** [comment]
The [Cardinal Components Item](https://github.com/OnyxStudios/Cardinal-Components-API) module, which this mod depends on, is incompatible with OptiFine due to normal OptiFine shenanigans (ie. invasive overwrites). I can't do anything to fix the issue (but OptiFabric may be able to patch it in the future).
