### ISSUE TITLE
[Suggestion] More Config Options for Balancing? 

### ISSUE THREAD

**Issue by Bossfuratu** [Draylar/inmis#105]
Right off the bat, I just want to mention that the ideas here are from how **[Quark](https://quarkmod.net/#features)  Oddities** handles their backpacks. Okay, cool.

I didn't know how else to reach out for suggestions, so I'm hoping it's okay here. I finally got to check out this mod, and after testing it for myself, I'm IN LOVE with all the customization options in the config. No other up-to-date backpack mod for Fabric has that quite yet. But despite being able to adjust the storage slots of each individual backpack, I'm finding the end result to still be a little overpowered..? As in, I don't want my server's players to prioritize backpacks over trying to obtain an Ender Chest, Shulker Box, or even a Llama - it overshadows what exists in Vanilla. Especially since you can have multiple backpacks in an inventory, take items out whenever, and even store items before giving it to somebody else like a package. So, here are some ideas that I'm essentially stealing from Quark Oddities' backpacks:

- A configuration option to only allow the player to access a backpack's inventory if it's in their armor's chest slot (or in the designated Trinkets slot).
     + Additionally, allow a secondary option for the backpack to only be used in the armor chest slot INSTEAD of Trinket's backslot.
     + Furthermore, allow another secondary option that would make unequipping a backpack impossible if it still has items inside.
- A configuration option that has it to where if the player dies, objects inside a backpack will scatter out of it.

• _Not a configuration option but still wanted to squeeze it in here: the ability to dye the leather backpacks. After all, they're leather._ 

So yeah, these configuration options ESPECIALLY used all together (including the already existing option to change the slot sizes) I believe would add more balance options to the config that players or server owners would find extremely useful. In conjunction, the backpacks are still useful and worth working towards... But it would also prevent players from ignoring other storage options from Vanilla.

I mainly wanted to post this not only because it's something I'd like to see, but I've seen other people post similar stuff like "Make it to where players can only have one backpack" but wouldn't have an idea on how to properly implement said idea. So even though I'm already typing this entire thing out knowing all this probably won't be put into the config options, it's worth a shot to put this out here in hopes that you and others MIGHT see this?

Thank you for making this mod, and I'll continue to watch and follow it with GREAT interest.

**Comment by Draylar** [comment]
Done, done, & done!

> A configuration option to only allow the player to access a backpack's inventory if it's in their armor's chest slot (or in the designated Trinkets slot).

`requireArmorTrinketToOpen` (default: false) will disable right-click backpack opening & opening through the `B` key for backpacks not in the armor/trinket inventory.

> Additionally, allow a secondary option for the backpack to only be used in the armor chest slot INSTEAD of Trinket's backslot.

`allowBackpacksInChestplate` (default: true) and `enableTrinketCompatibility` (default: true) will allow you to disable either mechanic.

> Furthermore, allow another secondary option that would make unequipping a backpack impossible if it still has items inside.

`requireEmptyForUnequip` (default: false) - works for the trinket and armor inventory.

> A configuration option that has it to where if the player dies, objects inside a backpack will scatter out of it.

`spillArmorBackpacksOnDeath` and `spillMainBackpacksOnDeath` will allow you to pick which inventory you want to empty out on death. The backpack will retain data (such as re-name or color) when dropped.

>  Not a configuration option but still wanted to squeeze it in here: the ability to dye the leather backpacks. After all, they're leather.

![image](https://user-images.githubusercontent.com/17728338/150005215-9d41bdac-4d80-4e38-ad6f-1d78d9f7e68a.png)

---

I'm going to push this out as a beta release (mostly because I touched a *lot* of stuff, and while I did test pretty thoroughly, I expect some things to break). Thank you for the time you spent crafting up this suggestion document - I really appreciate the thorough detail and explanations for each mechanic. Please let me know if you run into any issues with the next release - the .jar will be pushed out to CF as soon as I clean up some other issues in the next hour.
