### ISSUE TITLE
Compatibility with inventory sorting mods.

### ISSUE THREAD

**Issue by calloatti** [Draylar/inmis#13]
Can this be made compatible with inventory sorting mods like https://www.curseforge.com/minecraft/mc-mods/inventory-sorting please?

![image](https://user-images.githubusercontent.com/12817862/82679837-d8994a80-9c21-11ea-96f8-60ee8c181ef7.png)

It works for expanded storage chests, don't see why it should not work for these backpacks too:

![image](https://user-images.githubusercontent.com/12817862/82679916-f797dc80-9c21-11ea-8038-f79b3ae552c5.png)

**Comment by Draylar** [comment]
This would be on Inventory Sorting or [Spinnery](https://github.com/vini2003/Spinnery/issues) to fix. [This comment](https://github.com/kyrptonaught/Inventory-Sorter/issues/22#issuecomment-634500893) seems to imply Inventory Sorting will offer the fix, but I can talk to vini if it's not resolved.

I don't plan on moving to vanilla containers, mostly because it would require an entire rewrite of the mod (and I would prefer to use Spinnery anyways).
