### ISSUE TITLE
 Back pack clearing name

### ISSUE THREAD

**Issue by Tkvgamer** [Draylar/inmis#7]
If you name a backpack and then open it the name will be reset

**Comment by Draylar** [comment]
I'm trying to replicate this on the latest version (2.0.0-SNAPSHOT) without luck (backpack keeps name). Guessing it was unintentionally fixed somehow. Tell me if you find that the issue is still reproducable.

**Steps taken to attempt to reproduce:**
   - get Frayed Backpack in creative
   - rename to _Yeet_ in an anvil
   - open backpack
   - name persists
